### ISSUE TITLE
Driver return Status 500

### ISSUE THREAD

**Issue by BernhardFuchs** [iotexproject/uni-resolver-driver-did-io#2]
When resolving the example did `did:io:0x476c81C27036D05cB5ebfe30ae58C23351a61C4A` the uni-resolver return following error:
```
[internalError] Driver cannot retrieve resolve result for did:io:0x476c81C27036D05cB5ebfe30ae58C23351a61C4A from http://uni-resolver-driver-did-io:8080/1.0/identifiers/did:io:0x476c81C27036D05cB5ebfe30ae58C23351a61C4A: uni-resolver-driver-did-io:8080 failed to respond
```

Inside the container we can see these logs:
```
2021/08/21 08:27:19 http: panic serving 192.168.40.210:5894: runtime error: invalid memory address or nil pointer dereference
goroutine 7653 [running]:
net/http.(*conn).serve.func1(0xc000118960)
	/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0x6b1cc0, 0x93d3b0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
main.get(0xc00001d0c0, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/apps/proxy/main.go:19 +0x207
main.redirect(0x7742a0, 0xc0000bad20, 0xc000132200)
	/go/apps/proxy/main.go:32 +0x128
net/http.HandlerFunc.ServeHTTP(0x723428, 0x7742a0, 0xc0000bad20, 0xc000132200)
	/usr/local/go/src/net/http/server.go:2007 +0x44
net/http.(*ServeMux).ServeHTTP(0x9499e0, 0x7742a0, 0xc0000bad20, 0xc000132200)
	/usr/local/go/src/net/http/server.go:2387 +0x1bd
net/http.serverHandler.ServeHTTP(0xc0000ba000, 0x7742a0, 0xc0000bad20, 0xc000132200)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc000118960, 0x774820, 0xc00014ff80)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2928 +0x384
```

**Note** We have updated our [policies](https://github.com/decentralized-identity/universal-resolver/blob/main/docs/driver-development.md#how-we-handle-problems-with-drivers) and will, temporarily, remove broken drivers after ~30 days from the universal resolver deployment.

**Comment by millken** [comment]
> http://uni-resolver-driver-did-io:8080/1.0/identifiers/did:io:0x476c81C27036D05cB5ebfe30ae58C23351a61C4A: uni-resolver-driver-did-io:8080 failed to respond

It seems like container internal domain resolver problem, please confirm `uni-resolver-driver-did-io`  can be resolved internally.
